# Write Kubernetes Deployment Script
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog
spec:
  replicas: 2  # Number of pod replicas
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
        - name: book-catalog
          image: book-catalog:latest  # Replace with your Docker image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000  # The port your FastAPI app runs on
          env:
            - name: DATABASE_URL
              value: "postgresql://sit722_part2_kyp1_user:sKyYJozk9XnxX8jUy3dZlWBt9uwZMYRx@dpg-cr43r188fa8c73dfu7pg-a.oregon-postgres.render.com/sit722_part2_kyp1"  # Replace with your actual database URL

---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog
spec:
  selector:
    app: book-catalog
  type: NodePort  # Or "ClusterIP" if you don't need external access
  ports:
    - protocol: TCP
      port: 80  # Port exposed by the service
      targetPort: 8000  # Port your FastAPI app runs on
      nodePort: 30000


